sudo: required

language: c

services:
  - docker

before_install:
  - docker run -d --name influxdb -p 8086:8086 -p 8089:8089/udp -v $PWD/integration/influxdb.conf:/etc/influxdb/influxdb.conf:ro influxdb

script:
  - ./integration/nginx-tests.sh $PWD

after_script:
  - docker run -it -d influxdb --entrypoint=sh --net=host influx -execute 'select * from mymeasures' -database=testmod
